version: '3.8'

services:
  app:
    build: .
    ports:
      - '7777:7777'
    depends_on:
      - db
      - primary-json-server
      - secondary-json-server
      - tertiary-json-server
    env_file:
      - .env
    command: ["npm", "run", "start:prod"]

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - '5432:5432'

  primary-json-server:
    image: clue/json-server
    volumes:
      - ./primary-products.json:/data/primary-products.json
    ports:
      - '8001:80'

  secondary-json-server:
    image: clue/json-server
    volumes:
      - ./secondary-products.json:/data/secondary-products.json
    ports:
      - '8002:80'

  tertiary-json-server:
    image: clue/json-server
    volumes:
      - ./tertiary-products.json:/data/tertiary-products.json
    ports:
      - '8003:80'
